/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tokyocabinet_BDBCUR */

#ifndef _Included_tokyocabinet_BDBCUR
#define _Included_tokyocabinet_BDBCUR
#ifdef __cplusplus
extern "C" {
#endif
#undef tokyocabinet_BDBCUR_CPCURRENT
#define tokyocabinet_BDBCUR_CPCURRENT 0L
#undef tokyocabinet_BDBCUR_CPBEFORE
#define tokyocabinet_BDBCUR_CPBEFORE 1L
#undef tokyocabinet_BDBCUR_CPAFTER
#define tokyocabinet_BDBCUR_CPAFTER 2L
/*
 * Class:     tokyocabinet_BDBCUR
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_BDBCUR_init
  (JNIEnv *, jclass);

/*
 * Class:     tokyocabinet_BDBCUR
 * Method:    first
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_BDBCUR_first
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_BDBCUR
 * Method:    last
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_BDBCUR_last
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_BDBCUR
 * Method:    jump
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_BDBCUR_jump
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tokyocabinet_BDBCUR
 * Method:    prev
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_BDBCUR_prev
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_BDBCUR
 * Method:    next
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_BDBCUR_next
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_BDBCUR
 * Method:    put
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_BDBCUR_put
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     tokyocabinet_BDBCUR
 * Method:    out
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_BDBCUR_out
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_BDBCUR
 * Method:    key
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_tokyocabinet_BDBCUR_key
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_BDBCUR
 * Method:    val
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_tokyocabinet_BDBCUR_val
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_BDBCUR
 * Method:    initialize
 * Signature: (Ltokyocabinet/BDB;)V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_BDBCUR_initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     tokyocabinet_BDBCUR
 * Method:    destruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_BDBCUR_destruct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
