/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tokyocabinet_ADB */

#ifndef _Included_tokyocabinet_ADB
#define _Included_tokyocabinet_ADB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tokyocabinet_ADB
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_ADB_init
  (JNIEnv *, jclass);

/*
 * Class:     tokyocabinet_ADB
 * Method:    open
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_ADB_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tokyocabinet_ADB
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_ADB_close
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_ADB
 * Method:    put
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_ADB_put
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     tokyocabinet_ADB
 * Method:    putkeep
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_ADB_putkeep
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     tokyocabinet_ADB
 * Method:    putcat
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_ADB_putcat
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     tokyocabinet_ADB
 * Method:    out
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_ADB_out
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tokyocabinet_ADB
 * Method:    get
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tokyocabinet_ADB_get
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tokyocabinet_ADB
 * Method:    vsiz
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_tokyocabinet_ADB_vsiz
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tokyocabinet_ADB
 * Method:    iterinit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_ADB_iterinit
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_ADB
 * Method:    iternext
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_tokyocabinet_ADB_iternext
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_ADB
 * Method:    fwmkeys
 * Signature: ([BI)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_tokyocabinet_ADB_fwmkeys
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     tokyocabinet_ADB
 * Method:    addint
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_tokyocabinet_ADB_addint
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     tokyocabinet_ADB
 * Method:    adddouble
 * Signature: ([BD)D
 */
JNIEXPORT jdouble JNICALL Java_tokyocabinet_ADB_adddouble
  (JNIEnv *, jobject, jbyteArray, jdouble);

/*
 * Class:     tokyocabinet_ADB
 * Method:    sync
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_ADB_sync
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_ADB
 * Method:    optimize
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_ADB_optimize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tokyocabinet_ADB
 * Method:    vanish
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_ADB_vanish
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_ADB
 * Method:    copy
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_ADB_copy
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tokyocabinet_ADB
 * Method:    tranbegin
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_ADB_tranbegin
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_ADB
 * Method:    trancommit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_ADB_trancommit
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_ADB
 * Method:    tranabort
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_ADB_tranabort
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_ADB
 * Method:    path
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tokyocabinet_ADB_path
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_ADB
 * Method:    rnum
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tokyocabinet_ADB_rnum
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_ADB
 * Method:    size
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tokyocabinet_ADB_size
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_ADB
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_ADB_initialize
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_ADB
 * Method:    destruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_ADB_destruct
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_ADB
 * Method:    miscimpl
 * Signature: (Ljava/lang/String;[[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_tokyocabinet_ADB_miscimpl
  (JNIEnv *, jobject, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
