/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tokyocabinet_FDB */

#ifndef _Included_tokyocabinet_FDB
#define _Included_tokyocabinet_FDB
#ifdef __cplusplus
extern "C" {
#endif
#undef tokyocabinet_FDB_ESUCCESS
#define tokyocabinet_FDB_ESUCCESS 0L
#undef tokyocabinet_FDB_ETHREAD
#define tokyocabinet_FDB_ETHREAD 1L
#undef tokyocabinet_FDB_EINVALID
#define tokyocabinet_FDB_EINVALID 2L
#undef tokyocabinet_FDB_ENOFILE
#define tokyocabinet_FDB_ENOFILE 3L
#undef tokyocabinet_FDB_ENOPERM
#define tokyocabinet_FDB_ENOPERM 4L
#undef tokyocabinet_FDB_EMETA
#define tokyocabinet_FDB_EMETA 5L
#undef tokyocabinet_FDB_ERHEAD
#define tokyocabinet_FDB_ERHEAD 6L
#undef tokyocabinet_FDB_EOPEN
#define tokyocabinet_FDB_EOPEN 7L
#undef tokyocabinet_FDB_ECLOSE
#define tokyocabinet_FDB_ECLOSE 8L
#undef tokyocabinet_FDB_ETRUNC
#define tokyocabinet_FDB_ETRUNC 9L
#undef tokyocabinet_FDB_ESYNC
#define tokyocabinet_FDB_ESYNC 10L
#undef tokyocabinet_FDB_ESTAT
#define tokyocabinet_FDB_ESTAT 11L
#undef tokyocabinet_FDB_ESEEK
#define tokyocabinet_FDB_ESEEK 12L
#undef tokyocabinet_FDB_EREAD
#define tokyocabinet_FDB_EREAD 13L
#undef tokyocabinet_FDB_EWRITE
#define tokyocabinet_FDB_EWRITE 14L
#undef tokyocabinet_FDB_EMMAP
#define tokyocabinet_FDB_EMMAP 15L
#undef tokyocabinet_FDB_ELOCK
#define tokyocabinet_FDB_ELOCK 16L
#undef tokyocabinet_FDB_EUNLINK
#define tokyocabinet_FDB_EUNLINK 17L
#undef tokyocabinet_FDB_ERENAME
#define tokyocabinet_FDB_ERENAME 18L
#undef tokyocabinet_FDB_EMKDIR
#define tokyocabinet_FDB_EMKDIR 19L
#undef tokyocabinet_FDB_ERMDIR
#define tokyocabinet_FDB_ERMDIR 20L
#undef tokyocabinet_FDB_EKEEP
#define tokyocabinet_FDB_EKEEP 21L
#undef tokyocabinet_FDB_ENOREC
#define tokyocabinet_FDB_ENOREC 22L
#undef tokyocabinet_FDB_EMISC
#define tokyocabinet_FDB_EMISC 9999L
#undef tokyocabinet_FDB_OREADER
#define tokyocabinet_FDB_OREADER 1L
#undef tokyocabinet_FDB_OWRITER
#define tokyocabinet_FDB_OWRITER 2L
#undef tokyocabinet_FDB_OCREAT
#define tokyocabinet_FDB_OCREAT 4L
#undef tokyocabinet_FDB_OTRUNC
#define tokyocabinet_FDB_OTRUNC 8L
#undef tokyocabinet_FDB_ONOLCK
#define tokyocabinet_FDB_ONOLCK 16L
#undef tokyocabinet_FDB_OLCKNB
#define tokyocabinet_FDB_OLCKNB 32L
/*
 * Class:     tokyocabinet_FDB
 * Method:    errmsg
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tokyocabinet_FDB_errmsg
  (JNIEnv *, jclass, jint);

/*
 * Class:     tokyocabinet_FDB
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_FDB_init
  (JNIEnv *, jclass);

/*
 * Class:     tokyocabinet_FDB
 * Method:    ecode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tokyocabinet_FDB_ecode
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_FDB
 * Method:    tune
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_FDB_tune
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     tokyocabinet_FDB
 * Method:    open
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_FDB_open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     tokyocabinet_FDB
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_FDB_close
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_FDB
 * Method:    put
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_FDB_put
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     tokyocabinet_FDB
 * Method:    putkeep
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_FDB_putkeep
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     tokyocabinet_FDB
 * Method:    putcat
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_FDB_putcat
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     tokyocabinet_FDB
 * Method:    out
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_FDB_out
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tokyocabinet_FDB
 * Method:    get
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tokyocabinet_FDB_get
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tokyocabinet_FDB
 * Method:    vsiz
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_tokyocabinet_FDB_vsiz
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tokyocabinet_FDB
 * Method:    iterinit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_FDB_iterinit
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_FDB
 * Method:    iternext
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_tokyocabinet_FDB_iternext
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_FDB
 * Method:    range
 * Signature: ([BI)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_tokyocabinet_FDB_range
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     tokyocabinet_FDB
 * Method:    addint
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_tokyocabinet_FDB_addint
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     tokyocabinet_FDB
 * Method:    adddouble
 * Signature: ([BD)D
 */
JNIEXPORT jdouble JNICALL Java_tokyocabinet_FDB_adddouble
  (JNIEnv *, jobject, jbyteArray, jdouble);

/*
 * Class:     tokyocabinet_FDB
 * Method:    sync
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_FDB_sync
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_FDB
 * Method:    optimize
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_FDB_optimize
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     tokyocabinet_FDB
 * Method:    vanish
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_FDB_vanish
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_FDB
 * Method:    copy
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_FDB_copy
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tokyocabinet_FDB
 * Method:    tranbegin
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_FDB_tranbegin
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_FDB
 * Method:    trancommit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_FDB_trancommit
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_FDB
 * Method:    tranabort
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_FDB_tranabort
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_FDB
 * Method:    path
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tokyocabinet_FDB_path
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_FDB
 * Method:    rnum
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tokyocabinet_FDB_rnum
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_FDB
 * Method:    fsiz
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tokyocabinet_FDB_fsiz
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_FDB
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_FDB_initialize
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_FDB
 * Method:    destruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_FDB_destruct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
