/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tokyocabinet_Util */

#ifndef _Included_tokyocabinet_Util
#define _Included_tokyocabinet_Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tokyocabinet_Util
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_Util_init
  (JNIEnv *, jclass);

/*
 * Class:     tokyocabinet_Util
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tokyocabinet_Util_version
  (JNIEnv *, jclass);

/*
 * Class:     tokyocabinet_Util
 * Method:    packint
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tokyocabinet_Util_packint
  (JNIEnv *, jclass, jint);

/*
 * Class:     tokyocabinet_Util
 * Method:    unpackint
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_tokyocabinet_Util_unpackint
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     tokyocabinet_Util
 * Method:    packdouble
 * Signature: (D)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tokyocabinet_Util_packdouble
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     tokyocabinet_Util
 * Method:    unpackdouble
 * Signature: ([B)D
 */
JNIEXPORT jdouble JNICALL Java_tokyocabinet_Util_unpackdouble
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     tokyocabinet_Util
 * Method:    system
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_tokyocabinet_Util_system
  (JNIEnv *, jclass, jstring);

/*
 * Class:     tokyocabinet_Util
 * Method:    chdir
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_tokyocabinet_Util_chdir
  (JNIEnv *, jclass, jstring);

/*
 * Class:     tokyocabinet_Util
 * Method:    getcwd
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tokyocabinet_Util_getcwd
  (JNIEnv *, jclass);

/*
 * Class:     tokyocabinet_Util
 * Method:    getpid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tokyocabinet_Util_getpid
  (JNIEnv *, jclass);

/*
 * Class:     tokyocabinet_Util
 * Method:    putenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_tokyocabinet_Util_putenv
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     tokyocabinet_Util
 * Method:    getenv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tokyocabinet_Util_getenv
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
