/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tokyocabinet_TDBQRY */

#ifndef _Included_tokyocabinet_TDBQRY
#define _Included_tokyocabinet_TDBQRY
#ifdef __cplusplus
extern "C" {
#endif
#undef tokyocabinet_TDBQRY_QCSTREQ
#define tokyocabinet_TDBQRY_QCSTREQ 0L
#undef tokyocabinet_TDBQRY_QCSTRINC
#define tokyocabinet_TDBQRY_QCSTRINC 1L
#undef tokyocabinet_TDBQRY_QCSTRBW
#define tokyocabinet_TDBQRY_QCSTRBW 2L
#undef tokyocabinet_TDBQRY_QCSTREW
#define tokyocabinet_TDBQRY_QCSTREW 3L
#undef tokyocabinet_TDBQRY_QCSTRAND
#define tokyocabinet_TDBQRY_QCSTRAND 4L
#undef tokyocabinet_TDBQRY_QCSTROR
#define tokyocabinet_TDBQRY_QCSTROR 5L
#undef tokyocabinet_TDBQRY_QCSTROREQ
#define tokyocabinet_TDBQRY_QCSTROREQ 6L
#undef tokyocabinet_TDBQRY_QCSTRRX
#define tokyocabinet_TDBQRY_QCSTRRX 7L
#undef tokyocabinet_TDBQRY_QCNUMEQ
#define tokyocabinet_TDBQRY_QCNUMEQ 8L
#undef tokyocabinet_TDBQRY_QCNUMGT
#define tokyocabinet_TDBQRY_QCNUMGT 9L
#undef tokyocabinet_TDBQRY_QCNUMGE
#define tokyocabinet_TDBQRY_QCNUMGE 10L
#undef tokyocabinet_TDBQRY_QCNUMLT
#define tokyocabinet_TDBQRY_QCNUMLT 11L
#undef tokyocabinet_TDBQRY_QCNUMLE
#define tokyocabinet_TDBQRY_QCNUMLE 12L
#undef tokyocabinet_TDBQRY_QCNUMBT
#define tokyocabinet_TDBQRY_QCNUMBT 13L
#undef tokyocabinet_TDBQRY_QCNUMOREQ
#define tokyocabinet_TDBQRY_QCNUMOREQ 14L
#undef tokyocabinet_TDBQRY_QCFTSPH
#define tokyocabinet_TDBQRY_QCFTSPH 15L
#undef tokyocabinet_TDBQRY_QCFTSAND
#define tokyocabinet_TDBQRY_QCFTSAND 16L
#undef tokyocabinet_TDBQRY_QCFTSOR
#define tokyocabinet_TDBQRY_QCFTSOR 17L
#undef tokyocabinet_TDBQRY_QCFTSEX
#define tokyocabinet_TDBQRY_QCFTSEX 18L
#undef tokyocabinet_TDBQRY_QCNEGATE
#define tokyocabinet_TDBQRY_QCNEGATE 16777216L
#undef tokyocabinet_TDBQRY_QCNOIDX
#define tokyocabinet_TDBQRY_QCNOIDX 33554432L
#undef tokyocabinet_TDBQRY_QOSTRASC
#define tokyocabinet_TDBQRY_QOSTRASC 0L
#undef tokyocabinet_TDBQRY_QOSTRDESC
#define tokyocabinet_TDBQRY_QOSTRDESC 1L
#undef tokyocabinet_TDBQRY_QONUMASC
#define tokyocabinet_TDBQRY_QONUMASC 2L
#undef tokyocabinet_TDBQRY_QONUMDESC
#define tokyocabinet_TDBQRY_QONUMDESC 3L
#undef tokyocabinet_TDBQRY_MSUNION
#define tokyocabinet_TDBQRY_MSUNION 0L
#undef tokyocabinet_TDBQRY_MSISECT
#define tokyocabinet_TDBQRY_MSISECT 1L
#undef tokyocabinet_TDBQRY_MSDIFF
#define tokyocabinet_TDBQRY_MSDIFF 2L
#undef tokyocabinet_TDBQRY_KWMUTAB
#define tokyocabinet_TDBQRY_KWMUTAB 1L
#undef tokyocabinet_TDBQRY_KWMUCTRL
#define tokyocabinet_TDBQRY_KWMUCTRL 2L
#undef tokyocabinet_TDBQRY_KWMUBRCT
#define tokyocabinet_TDBQRY_KWMUBRCT 4L
#undef tokyocabinet_TDBQRY_KWNOOVER
#define tokyocabinet_TDBQRY_KWNOOVER 16777216L
#undef tokyocabinet_TDBQRY_KWPULEAD
#define tokyocabinet_TDBQRY_KWPULEAD 33554432L
/*
 * Class:     tokyocabinet_TDBQRY
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_TDBQRY_init
  (JNIEnv *, jclass);

/*
 * Class:     tokyocabinet_TDBQRY
 * Method:    addcond
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_TDBQRY_addcond
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     tokyocabinet_TDBQRY
 * Method:    setorder
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_TDBQRY_setorder
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     tokyocabinet_TDBQRY
 * Method:    setlimit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_TDBQRY_setlimit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     tokyocabinet_TDBQRY
 * Method:    search
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_tokyocabinet_TDBQRY_search
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_TDBQRY
 * Method:    searchout
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_TDBQRY_searchout
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_TDBQRY
 * Method:    proc
 * Signature: (Ltokyocabinet/TDBQRYPROC;)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_TDBQRY_proc
  (JNIEnv *, jobject, jobject);

/*
 * Class:     tokyocabinet_TDBQRY
 * Method:    hint
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tokyocabinet_TDBQRY_hint
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_TDBQRY
 * Method:    metasearch
 * Signature: ([Ltokyocabinet/TDBQRY;I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_tokyocabinet_TDBQRY_metasearch
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     tokyocabinet_TDBQRY
 * Method:    initialize
 * Signature: (Ltokyocabinet/TDB;)V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_TDBQRY_initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     tokyocabinet_TDBQRY
 * Method:    destruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_TDBQRY_destruct
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_TDBQRY
 * Method:    kwicimpl
 * Signature: ([[BLjava/lang/String;II)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_tokyocabinet_TDBQRY_kwicimpl
  (JNIEnv *, jobject, jobjectArray, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
