/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tokyocabinet_HDB */

#ifndef _Included_tokyocabinet_HDB
#define _Included_tokyocabinet_HDB
#ifdef __cplusplus
extern "C" {
#endif
#undef tokyocabinet_HDB_ESUCCESS
#define tokyocabinet_HDB_ESUCCESS 0L
#undef tokyocabinet_HDB_ETHREAD
#define tokyocabinet_HDB_ETHREAD 1L
#undef tokyocabinet_HDB_EINVALID
#define tokyocabinet_HDB_EINVALID 2L
#undef tokyocabinet_HDB_ENOFILE
#define tokyocabinet_HDB_ENOFILE 3L
#undef tokyocabinet_HDB_ENOPERM
#define tokyocabinet_HDB_ENOPERM 4L
#undef tokyocabinet_HDB_EMETA
#define tokyocabinet_HDB_EMETA 5L
#undef tokyocabinet_HDB_ERHEAD
#define tokyocabinet_HDB_ERHEAD 6L
#undef tokyocabinet_HDB_EOPEN
#define tokyocabinet_HDB_EOPEN 7L
#undef tokyocabinet_HDB_ECLOSE
#define tokyocabinet_HDB_ECLOSE 8L
#undef tokyocabinet_HDB_ETRUNC
#define tokyocabinet_HDB_ETRUNC 9L
#undef tokyocabinet_HDB_ESYNC
#define tokyocabinet_HDB_ESYNC 10L
#undef tokyocabinet_HDB_ESTAT
#define tokyocabinet_HDB_ESTAT 11L
#undef tokyocabinet_HDB_ESEEK
#define tokyocabinet_HDB_ESEEK 12L
#undef tokyocabinet_HDB_EREAD
#define tokyocabinet_HDB_EREAD 13L
#undef tokyocabinet_HDB_EWRITE
#define tokyocabinet_HDB_EWRITE 14L
#undef tokyocabinet_HDB_EMMAP
#define tokyocabinet_HDB_EMMAP 15L
#undef tokyocabinet_HDB_ELOCK
#define tokyocabinet_HDB_ELOCK 16L
#undef tokyocabinet_HDB_EUNLINK
#define tokyocabinet_HDB_EUNLINK 17L
#undef tokyocabinet_HDB_ERENAME
#define tokyocabinet_HDB_ERENAME 18L
#undef tokyocabinet_HDB_EMKDIR
#define tokyocabinet_HDB_EMKDIR 19L
#undef tokyocabinet_HDB_ERMDIR
#define tokyocabinet_HDB_ERMDIR 20L
#undef tokyocabinet_HDB_EKEEP
#define tokyocabinet_HDB_EKEEP 21L
#undef tokyocabinet_HDB_ENOREC
#define tokyocabinet_HDB_ENOREC 22L
#undef tokyocabinet_HDB_EMISC
#define tokyocabinet_HDB_EMISC 9999L
#undef tokyocabinet_HDB_TLARGE
#define tokyocabinet_HDB_TLARGE 1L
#undef tokyocabinet_HDB_TDEFLATE
#define tokyocabinet_HDB_TDEFLATE 2L
#undef tokyocabinet_HDB_TBZIP
#define tokyocabinet_HDB_TBZIP 4L
#undef tokyocabinet_HDB_TTCBS
#define tokyocabinet_HDB_TTCBS 8L
#undef tokyocabinet_HDB_OREADER
#define tokyocabinet_HDB_OREADER 1L
#undef tokyocabinet_HDB_OWRITER
#define tokyocabinet_HDB_OWRITER 2L
#undef tokyocabinet_HDB_OCREAT
#define tokyocabinet_HDB_OCREAT 4L
#undef tokyocabinet_HDB_OTRUNC
#define tokyocabinet_HDB_OTRUNC 8L
#undef tokyocabinet_HDB_ONOLCK
#define tokyocabinet_HDB_ONOLCK 16L
#undef tokyocabinet_HDB_OLCKNB
#define tokyocabinet_HDB_OLCKNB 32L
#undef tokyocabinet_HDB_OTSYNC
#define tokyocabinet_HDB_OTSYNC 64L
/*
 * Class:     tokyocabinet_HDB
 * Method:    errmsg
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tokyocabinet_HDB_errmsg
  (JNIEnv *, jclass, jint);

/*
 * Class:     tokyocabinet_HDB
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_HDB_init
  (JNIEnv *, jclass);

/*
 * Class:     tokyocabinet_HDB
 * Method:    ecode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tokyocabinet_HDB_ecode
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_HDB
 * Method:    tune
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_tune
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     tokyocabinet_HDB
 * Method:    setcache
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_setcache
  (JNIEnv *, jobject, jint);

/*
 * Class:     tokyocabinet_HDB
 * Method:    setxmsiz
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_setxmsiz
  (JNIEnv *, jobject, jlong);

/*
 * Class:     tokyocabinet_HDB
 * Method:    setdfunit
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_setdfunit
  (JNIEnv *, jobject, jint);

/*
 * Class:     tokyocabinet_HDB
 * Method:    open
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     tokyocabinet_HDB
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_close
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_HDB
 * Method:    put
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_put
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     tokyocabinet_HDB
 * Method:    putkeep
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_putkeep
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     tokyocabinet_HDB
 * Method:    putcat
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_putcat
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     tokyocabinet_HDB
 * Method:    putasync
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_putasync
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     tokyocabinet_HDB
 * Method:    out
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_out
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tokyocabinet_HDB
 * Method:    get
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tokyocabinet_HDB_get
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tokyocabinet_HDB
 * Method:    vsiz
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_tokyocabinet_HDB_vsiz
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tokyocabinet_HDB
 * Method:    iterinit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_iterinit
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_HDB
 * Method:    iternext
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_tokyocabinet_HDB_iternext
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_HDB
 * Method:    fwmkeys
 * Signature: ([BI)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_tokyocabinet_HDB_fwmkeys
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     tokyocabinet_HDB
 * Method:    addint
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_tokyocabinet_HDB_addint
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     tokyocabinet_HDB
 * Method:    adddouble
 * Signature: ([BD)D
 */
JNIEXPORT jdouble JNICALL Java_tokyocabinet_HDB_adddouble
  (JNIEnv *, jobject, jbyteArray, jdouble);

/*
 * Class:     tokyocabinet_HDB
 * Method:    sync
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_sync
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_HDB
 * Method:    optimize
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_optimize
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     tokyocabinet_HDB
 * Method:    vanish
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_vanish
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_HDB
 * Method:    copy
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_copy
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tokyocabinet_HDB
 * Method:    tranbegin
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_tranbegin
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_HDB
 * Method:    trancommit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_trancommit
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_HDB
 * Method:    tranabort
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyocabinet_HDB_tranabort
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_HDB
 * Method:    path
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tokyocabinet_HDB_path
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_HDB
 * Method:    rnum
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tokyocabinet_HDB_rnum
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_HDB
 * Method:    fsiz
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tokyocabinet_HDB_fsiz
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_HDB
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_HDB_initialize
  (JNIEnv *, jobject);

/*
 * Class:     tokyocabinet_HDB
 * Method:    destruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyocabinet_HDB_destruct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
